let courses = [
  {
    "department": "IN4MATX",
    "fullCourseNumber": "43",
    "courseNumber": 43,
    "courseTitle": "INTRO SOFTWARE ENGR",
    "fullCourseTitle": "IN4MATX 43 INTRO SOFTWARE ENGR",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 330,
    "maxEnrollment": 330,
    "studentsWaitlisted": 26,
    "primaryInstructor": "MANNAN, U."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "113",
    "courseNumber": 113,
    "courseTitle": "REQT ANALYSIS & ENG",
    "fullCourseTitle": "IN4MATX 113 REQT ANALYSIS & ENG",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 248,
    "maxEnrollment": 248,
    "studentsWaitlisted": 31,
    "primaryInstructor": "NAVARRO, E."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "115",
    "courseNumber": 115,
    "courseTitle": "SW TEST&QUAL ASSUR",
    "fullCourseTitle": "IN4MATX 115 SW TEST&QUAL ASSUR",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 279,
    "maxEnrollment": 300,
    "studentsWaitlisted": 0,
    "primaryInstructor": "AHMED, I."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "117",
    "courseNumber": 117,
    "courseTitle": "PROJ IN SFT SYS DES",
    "fullCourseTitle": "IN4MATX 117 PROJ IN SFT SYS DES",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 77,
    "maxEnrollment": 74,
    "studentsWaitlisted": 0,
    "primaryInstructor": "ZIV, H."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "121",
    "courseNumber": 121,
    "courseTitle": "SOFTWARE DESIGN I",
    "fullCourseTitle": "IN4MATX 121 SOFTWARE DESIGN I",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 249,
    "maxEnrollment": 249,
    "studentsWaitlisted": 18,
    "primaryInstructor": "NGUYEN, D."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "124",
    "courseNumber": 124,
    "courseTitle": "INTERNET APPS ENGR",
    "fullCourseTitle": "IN4MATX 124 INTERNET APPS ENGR",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 130,
    "maxEnrollment": 130,
    "studentsWaitlisted": 2,
    "primaryInstructor": "MOSHIRPOUR, M."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "131",
    "courseNumber": 131,
    "courseTitle": "HUMAN CMPTR INTRACT",
    "fullCourseTitle": "IN4MATX 131 HUMAN CMPTR INTRACT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 249,
    "maxEnrollment": 249,
    "studentsWaitlisted": 48,
    "primaryInstructor": "BRANHAM, S."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "132",
    "courseNumber": 132,
    "courseTitle": "ADV TOPICS IN HCI",
    "fullCourseTitle": "IN4MATX 132 ADV TOPICS IN HCI",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 130,
    "maxEnrollment": 130,
    "studentsWaitlisted": 26,
    "primaryInstructor": "PIPER, A."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "134",
    "courseNumber": 134,
    "courseTitle": "PROJ IN USER INT SW",
    "fullCourseTitle": "IN4MATX 134 PROJ IN USER INT SW",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 145,
    "maxEnrollment": 145,
    "studentsWaitlisted": 3,
    "primaryInstructor": "JAMBHEKAR, S."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "141",
    "courseNumber": 141,
    "courseTitle": "INFRMTION RETRIEVAL",
    "fullCourseTitle": "IN4MATX 141 INFRMTION RETRIEVAL",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 245,
    "maxEnrollment": 245,
    "studentsWaitlisted": 25,
    "primaryInstructor": "LOPES, C."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "143",
    "courseNumber": 143,
    "courseTitle": "INFRMTION VISUALZTN",
    "fullCourseTitle": "IN4MATX 143 INFRMTION VISUALZTN",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 249,
    "maxEnrollment": 249,
    "studentsWaitlisted": 14,
    "primaryInstructor": "AHMED, N."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "151",
    "courseNumber": 151,
    "courseTitle": "PROJECT MANAGEMENT",
    "fullCourseTitle": "IN4MATX 151 PROJECT MANAGEMENT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 191,
    "maxEnrollment": 191,
    "studentsWaitlisted": 11,
    "primaryInstructor": "JAMBHEKAR, S."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "153",
    "courseNumber": 153,
    "courseTitle": "CMPTR SUP COOP WORK",
    "fullCourseTitle": "IN4MATX 153 CMPTR SUP COOP WORK",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 130,
    "maxEnrollment": 130,
    "studentsWaitlisted": 4,
    "primaryInstructor": "MIN, A."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "164",
    "courseNumber": 164,
    "courseTitle": "CHILD LRNING &MEDIA",
    "fullCourseTitle": "IN4MATX 164 CHILD LRNING &MEDIA",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 180,
    "maxEnrollment": 180,
    "studentsWaitlisted": 20,
    "primaryInstructor": "PEPPLER, K."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "173",
    "courseNumber": 173,
    "courseTitle": "CONSUMER HEALTH INF",
    "fullCourseTitle": "IN4MATX 173 CONSUMER HEALTH INF",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 124,
    "maxEnrollment": 124,
    "studentsWaitlisted": 5,
    "primaryInstructor": "CHEN, Y."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "174",
    "courseNumber": 174,
    "courseTitle": "HEALTH DATA ANALYT",
    "fullCourseTitle": "IN4MATX 174 HEALTH DATA ANALYT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 150,
    "maxEnrollment": 150,
    "studentsWaitlisted": 7,
    "primaryInstructor": "ZHENG, K."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "191B",
    "courseNumber": 191,
    "courseTitle": "SENIOR DESIGN PROJ",
    "fullCourseTitle": "IN4MATX 191B SENIOR DESIGN PROJ",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 127,
    "maxEnrollment": 142,
    "studentsWaitlisted": 0,
    "primaryInstructor": "BIETZ, M. & ZIV, H."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "H198",
    "courseNumber": 198,
    "courseTitle": "HONORS RESEARCH",
    "fullCourseTitle": "IN4MATX H198 HONORS RESEARCH",
    "seminarCourse": true
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "199",
    "courseNumber": 199,
    "courseTitle": "INDIVIDUAL STUDY",
    "fullCourseTitle": "IN4MATX 199 INDIVIDUAL STUDY",
    "seminarCourse": true
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "207S",
    "courseNumber": 207,
    "courseTitle": "SEM RESRCH & WRITNG",
    "fullCourseTitle": "IN4MATX 207S SEM RESRCH & WRITNG",
    "seminarCourse": false,
    "units": 2,
    "studentsEnrolled": 7,
    "maxEnrollment": 12,
    "studentsWaitlisted": 0,
    "primaryInstructor": "REDDY, M."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "209S",
    "courseNumber": 209,
    "courseTitle": "SEMINAR INFORMATICS",
    "fullCourseTitle": "IN4MATX 209S SEMINAR INFORMATICS",
    "seminarCourse": false,
    "units": 2,
    "studentsEnrolled": 3,
    "maxEnrollment": 40,
    "studentsWaitlisted": 0,
    "primaryInstructor": "AGAPIE, E."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "244",
    "courseNumber": 244,
    "courseTitle": "INTR EMBED UBIQ SYS",
    "fullCourseTitle": "IN4MATX 244 INTR EMBED UBIQ SYS",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 32,
    "maxEnrollment": 60,
    "studentsWaitlisted": 0,
    "primaryInstructor": "BOZORGZADEH, E."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "273",
    "courseNumber": 273,
    "courseTitle": "INFO TECH GLOB SUST",
    "fullCourseTitle": "IN4MATX 273 INFO TECH GLOB SUST",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 9,
    "maxEnrollment": 30,
    "studentsWaitlisted": 0,
    "primaryInstructor": "TOMLINSON, W."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "285",
    "courseNumber": 285,
    "courseTitle": "INTERACTIVE TECH",
    "fullCourseTitle": "IN4MATX 285 INTERACTIVE TECH",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 44,
    "maxEnrollment": 44,
    "studentsWaitlisted": 0,
    "primaryInstructor": "EPSTEIN, D."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "287",
    "courseNumber": 287,
    "courseTitle": "CAPSTONE PROJECT",
    "fullCourseTitle": "IN4MATX 287 CAPSTONE PROJECT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 44,
    "maxEnrollment": 44,
    "studentsWaitlisted": 0,
    "primaryInstructor": "BIETZ, M."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "289",
    "courseNumber": 289,
    "courseTitle": "HCID IN INDUSTRY",
    "fullCourseTitle": "IN4MATX 289 HCID IN INDUSTRY",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 44,
    "maxEnrollment": 44,
    "studentsWaitlisted": 0,
    "primaryInstructor": "KOLKO, J."
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "290",
    "courseNumber": 290,
    "courseTitle": "RESEARCH SEMINAR",
    "fullCourseTitle": "IN4MATX 290 RESEARCH SEMINAR",
    "seminarCourse": true
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "298",
    "courseNumber": 298,
    "courseTitle": "THESIS SUPERVISION",
    "fullCourseTitle": "IN4MATX 298 THESIS SUPERVISION",
    "seminarCourse": true
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "299",
    "courseNumber": 299,
    "courseTitle": "INDIVIDUAL STUDY",
    "fullCourseTitle": "IN4MATX 299 INDIVIDUAL STUDY",
    "seminarCourse": true
  }
]