let courses_full = [
  {
    "department": "IN4MATX",
    "fullCourseNumber": "43",
    "courseNumber": 43,
    "courseTitle": "INTRO SOFTWARE ENGR",
    "fullCourseTitle": "IN4MATX 43 INTRO SOFTWARE ENGR",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 330,
    "maxEnrollment": 330,
    "studentsWaitlisted": 26,
    "primaryInstructor": "MANNAN, U.",
    "allClassActivities": [
      {
        "Code": 36000,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "MANNAN, U.",
        "Modality": "In-Person",
        "Time": "MWF 10:00-10:50",
        "Place": "EH 1200",
        "Final": "Mon, Jun 9, 10:30-12:30pm",
        "Max": 330,
        "Enr": 330,
        "WL": 26,
        "Req": 431,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36001,
        "Type": "Dis",
        "Sec": "A1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMANNAN, U.",
        "Modality": "In-Person",
        "Time": "F 8:00- 8:50",
        "Place": "ICS 180",
        "Final": "",
        "Max": 55,
        "Enr": 55,
        "WL": 6,
        "Req": 61,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36002,
        "Type": "Dis",
        "Sec": "A2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMANNAN, U.",
        "Modality": "In-Person",
        "Time": "F 9:00- 9:50",
        "Place": "ICS 180",
        "Final": "",
        "Max": 55,
        "Enr": 55,
        "WL": 5,
        "Req": 60,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36003,
        "Type": "Dis",
        "Sec": "A3",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMANNAN, U.",
        "Modality": "In-Person",
        "Time": "F 12:00-12:50p",
        "Place": "DBH 1200",
        "Final": "",
        "Max": 52,
        "Enr": 52,
        "WL": 3,
        "Req": 58,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36004,
        "Type": "Dis",
        "Sec": "A4",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMANNAN, U.",
        "Modality": "In-Person",
        "Time": "F 11:00-11:50",
        "Place": "ICS 180",
        "Final": "",
        "Max": 55,
        "Enr": 55,
        "WL": 5,
        "Req": 64,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36005,
        "Type": "Dis",
        "Sec": "A5",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMANNAN, U.",
        "Modality": "In-Person",
        "Time": "F 1:00- 1:50p",
        "Place": "MSTB 118",
        "Final": "",
        "Max": 56,
        "Enr": 56,
        "WL": 4,
        "Req": 64,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36006,
        "Type": "Dis",
        "Sec": "A6",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMANNAN, U.",
        "Modality": "In-Person",
        "Time": "F 2:00- 2:50p",
        "Place": "MSTB 118",
        "Final": "",
        "Max": 57,
        "Enr": 57,
        "WL": 6,
        "Req": 61,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "113",
    "courseNumber": 113,
    "courseTitle": "REQT ANALYSIS & ENG",
    "fullCourseTitle": "IN4MATX 113 REQT ANALYSIS & ENG",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 248,
    "maxEnrollment": 248,
    "studentsWaitlisted": 31,
    "primaryInstructor": "NAVARRO, E.",
    "allClassActivities": [
      {
        "Code": 36030,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "NAVARRO, E.",
        "Modality": "In-Person",
        "Time": "TuTh 9:30-10:50",
        "Place": "ALP 2300",
        "Final": "Thu, Jun 12, 8:00-10:00am",
        "Max": 248,
        "Enr": 248,
        "WL": 31,
        "Req": 430,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36031,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNAVARRO, E.",
        "Modality": "In-Person",
        "Time": "M 1:00- 1:50p",
        "Place": "MSTB 118",
        "Final": "",
        "Max": 62,
        "Enr": 62,
        "WL": 10,
        "Req": 75,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36032,
        "Type": "Dis",
        "Sec": "2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nSTAFF\n\n\nNAVARRO, E.",
        "Modality": "In-Person",
        "Time": "M 2:00- 2:50p",
        "Place": "MSTB 118",
        "Final": "",
        "Max": 62,
        "Enr": 62,
        "WL": 10,
        "Req": 65,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36033,
        "Type": "Dis",
        "Sec": "3",
        "Units": 0,
        "Instructor": "STAFF\n\n\nSTAFF\n\n\nNAVARRO, E.",
        "Modality": "In-Person",
        "Time": "M 4:00- 4:50p",
        "Place": "SH 174",
        "Final": "",
        "Max": 61,
        "Enr": 61,
        "WL": 10,
        "Req": 57,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36034,
        "Type": "Dis",
        "Sec": "4",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNAVARRO, E.",
        "Modality": "In-Person",
        "Time": "M 5:00- 5:50p",
        "Place": "SH 174",
        "Final": "",
        "Max": 63,
        "Enr": 63,
        "WL": 9,
        "Req": 48,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "115",
    "courseNumber": 115,
    "courseTitle": "SW TEST&QUAL ASSUR",
    "fullCourseTitle": "IN4MATX 115 SW TEST&QUAL ASSUR",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 279,
    "maxEnrollment": 300,
    "studentsWaitlisted": 0,
    "primaryInstructor": "AHMED, I.",
    "allClassActivities": [
      {
        "Code": 36040,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "AHMED, I.\n\n\nSTAFF\n\n\nSTAFF",
        "Modality": "In-Person",
        "Time": "TuTh 5:00- 6:20p",
        "Place": "SSLH 100",
        "Final": "Thu, Jun 12, 4:00-6:00pm",
        "Max": 300,
        "Enr": 279,
        "WL": 0,
        "Req": 375,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "117",
    "courseNumber": 117,
    "courseTitle": "PROJ IN SFT SYS DES",
    "fullCourseTitle": "IN4MATX 117 PROJ IN SFT SYS DES",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 77,
    "maxEnrollment": 74,
    "studentsWaitlisted": 0,
    "primaryInstructor": "ZIV, H.",
    "allClassActivities": [
      {
        "Code": 36050,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "ZIV, H.",
        "Modality": "In-Person",
        "Time": "TuTh 11:00-12:20p",
        "Place": "ALP 1700",
        "Final": "Tue, Jun 10, 10:30-12:30pm",
        "Max": 74,
        "Enr": 77,
        "WL": 0,
        "Req": 172,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "FULL"
      },
      {
        "Code": 36051,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nZIV, H.",
        "Modality": "In-Person",
        "Time": "F 9:00- 9:50",
        "Place": "SSL 140",
        "Final": "",
        "Max": 74,
        "Enr": 77,
        "WL": 0,
        "Req": 82,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "FULL"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "121",
    "courseNumber": 121,
    "courseTitle": "SOFTWARE DESIGN I",
    "fullCourseTitle": "IN4MATX 121 SOFTWARE DESIGN I",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 249,
    "maxEnrollment": 249,
    "studentsWaitlisted": 18,
    "primaryInstructor": "NGUYEN, D.",
    "allClassActivities": [
      {
        "Code": 36070,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "NGUYEN, D.",
        "Modality": "In-Person",
        "Time": "TuTh 12:30- 1:50p",
        "Place": "SSH 100",
        "Final": "Mon, Jun 9, 1:30-3:30pm",
        "Max": 249,
        "Enr": 249,
        "WL": 18,
        "Req": 404,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36071,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNGUYEN, D.",
        "Modality": "In-Person",
        "Time": "F 12:00-12:50p",
        "Place": "PCB 1200",
        "Final": "",
        "Max": 50,
        "Enr": 50,
        "WL": 12,
        "Req": 60,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36072,
        "Type": "Dis",
        "Sec": "2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNGUYEN, D.",
        "Modality": "In-Person",
        "Time": "F 1:00- 1:50p",
        "Place": "PCB 1200",
        "Final": "",
        "Max": 50,
        "Enr": 50,
        "WL": 7,
        "Req": 56,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36073,
        "Type": "Dis",
        "Sec": "3",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNGUYEN, D.",
        "Modality": "In-Person",
        "Time": "F 2:00- 2:50p",
        "Place": "PCB 1200",
        "Final": "",
        "Max": 50,
        "Enr": 50,
        "WL": 7,
        "Req": 53,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36074,
        "Type": "Dis",
        "Sec": "4",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNGUYEN, D.",
        "Modality": "In-Person",
        "Time": "F 3:00- 3:50p",
        "Place": "PCB 1200",
        "Final": "",
        "Max": 50,
        "Enr": 50,
        "WL": 4,
        "Req": 50,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36075,
        "Type": "Dis",
        "Sec": "5",
        "Units": 0,
        "Instructor": "STAFF\n\n\nNGUYEN, D.",
        "Modality": "In-Person",
        "Time": "F 4:00- 4:50p",
        "Place": "PCB 1200",
        "Final": "",
        "Max": 49,
        "Enr": 49,
        "WL": 3,
        "Req": 37,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "124",
    "courseNumber": 124,
    "courseTitle": "INTERNET APPS ENGR",
    "fullCourseTitle": "IN4MATX 124 INTERNET APPS ENGR",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 130,
    "maxEnrollment": 130,
    "studentsWaitlisted": 2,
    "primaryInstructor": "MOSHIRPOUR, M.",
    "allClassActivities": [
      {
        "Code": 36080,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "MOSHIRPOUR, M.",
        "Modality": "In-Person",
        "Time": "TuTh 12:30- 1:50p",
        "Place": "HH 178",
        "Final": "Mon, Jun 9, 1:30-3:30pm",
        "Max": 130,
        "Enr": 130,
        "WL": 2,
        "Req": 188,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36081,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMOSHIRPOUR, M.",
        "Modality": "In-Person",
        "Time": "M 11:00-11:50",
        "Place": "SH 128",
        "Final": "",
        "Max": 65,
        "Enr": 65,
        "WL": 1,
        "Req": 62,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36082,
        "Type": "Dis",
        "Sec": "2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nMOSHIRPOUR, M.",
        "Modality": "In-Person",
        "Time": "M 12:00-12:50p",
        "Place": "SH 128",
        "Final": "",
        "Max": 65,
        "Enr": 65,
        "WL": 1,
        "Req": 65,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "131",
    "courseNumber": 131,
    "courseTitle": "HUMAN CMPTR INTRACT",
    "fullCourseTitle": "IN4MATX 131 HUMAN CMPTR INTRACT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 249,
    "maxEnrollment": 249,
    "studentsWaitlisted": 48,
    "primaryInstructor": "BRANHAM, S.",
    "allClassActivities": [
      {
        "Code": 36100,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "BRANHAM, S.",
        "Modality": "In-Person",
        "Time": "TuTh 2:00- 3:20p",
        "Place": "ALP 1300",
        "Final": "Thu, Jun 12, 1:30-3:30pm",
        "Max": 249,
        "Enr": 249,
        "WL": 48,
        "Req": 445,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36101,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nBRANHAM, S.",
        "Modality": "In-Person",
        "Time": "W 9:00- 9:50",
        "Place": "SH 174",
        "Final": "",
        "Max": 62,
        "Enr": 62,
        "WL": 11,
        "Req": 59,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36102,
        "Type": "Dis",
        "Sec": "2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nBRANHAM, S.",
        "Modality": "In-Person",
        "Time": "W 10:00-10:50",
        "Place": "SH 174",
        "Final": "",
        "Max": 62,
        "Enr": 62,
        "WL": 14,
        "Req": 54,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36103,
        "Type": "Dis",
        "Sec": "3",
        "Units": 0,
        "Instructor": "STAFF\n\n\nSTAFF\n\n\nBRANHAM, S.",
        "Modality": "In-Person",
        "Time": "W 11:00-11:50",
        "Place": "SH 128",
        "Final": "",
        "Max": 62,
        "Enr": 62,
        "WL": 16,
        "Req": 57,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36104,
        "Type": "Dis",
        "Sec": "4",
        "Units": 0,
        "Instructor": "STAFF\n\n\nSTAFF\n\n\nBRANHAM, S.",
        "Modality": "In-Person",
        "Time": "W 12:00-12:50p",
        "Place": "SH 128",
        "Final": "",
        "Max": 63,
        "Enr": 63,
        "WL": 15,
        "Req": 74,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "132",
    "courseNumber": 132,
    "courseTitle": "ADV TOPICS IN HCI",
    "fullCourseTitle": "IN4MATX 132 ADV TOPICS IN HCI",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 130,
    "maxEnrollment": 130,
    "studentsWaitlisted": 26,
    "primaryInstructor": "PIPER, A.",
    "allClassActivities": [
      {
        "Code": 36110,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "PIPER, A.",
        "Modality": "In-Person",
        "Time": "MW 9:30-10:50",
        "Place": "HSLH 100A",
        "Final": "Wed, Jun 11, 8:00-10:00am",
        "Max": 130,
        "Enr": 130,
        "WL": 26,
        "Req": 223,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36111,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nPIPER, A.",
        "Modality": "In-Person",
        "Time": "F 1:00- 1:50p",
        "Place": "ICS 174",
        "Final": "",
        "Max": 65,
        "Enr": 65,
        "WL": 13,
        "Req": 88,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36112,
        "Type": "Dis",
        "Sec": "2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nPIPER, A.",
        "Modality": "In-Person",
        "Time": "F 3:00- 3:50p",
        "Place": "ICS 174",
        "Final": "",
        "Max": 65,
        "Enr": 65,
        "WL": 13,
        "Req": 80,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "134",
    "courseNumber": 134,
    "courseTitle": "PROJ IN USER INT SW",
    "fullCourseTitle": "IN4MATX 134 PROJ IN USER INT SW",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 145,
    "maxEnrollment": 145,
    "studentsWaitlisted": 3,
    "primaryInstructor": "JAMBHEKAR, S.",
    "allClassActivities": [
      {
        "Code": 36130,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "JAMBHEKAR, S.",
        "Modality": "In-Person",
        "Time": "MW 5:00- 6:20p",
        "Place": "BS3 1200",
        "Final": "TBA",
        "Max": 145,
        "Enr": 145,
        "WL": 3,
        "Req": 210,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "Web",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "141",
    "courseNumber": 141,
    "courseTitle": "INFRMTION RETRIEVAL",
    "fullCourseTitle": "IN4MATX 141 INFRMTION RETRIEVAL",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 245,
    "maxEnrollment": 245,
    "studentsWaitlisted": 25,
    "primaryInstructor": "LOPES, C.",
    "allClassActivities": [
      {
        "Code": 36150,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "LOPES, C.",
        "Modality": "In-Person",
        "Time": "TuTh 11:00-12:20p",
        "Place": "HIB 100",
        "Final": "Tue, Jun 10, 10:30-12:30pm",
        "Max": 245,
        "Enr": 245,
        "WL": 25,
        "Req": 134,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36151,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nLOPES, C.",
        "Modality": "In-Person",
        "Time": "F 9:00- 9:50",
        "Place": "SH 174",
        "Final": "",
        "Max": 60,
        "Enr": 60,
        "WL": 5,
        "Req": 12,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36152,
        "Type": "Dis",
        "Sec": "2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nLOPES, C.",
        "Modality": "In-Person",
        "Time": "F 10:00-10:50",
        "Place": "SH 174",
        "Final": "",
        "Max": 60,
        "Enr": 60,
        "WL": 8,
        "Req": 10,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36153,
        "Type": "Dis",
        "Sec": "3",
        "Units": 0,
        "Instructor": "STAFF\n\n\nLOPES, C.",
        "Modality": "In-Person",
        "Time": "F 12:00-12:50p",
        "Place": "SE2 1304",
        "Final": "",
        "Max": 62,
        "Enr": 62,
        "WL": 7,
        "Req": 23,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36154,
        "Type": "Dis",
        "Sec": "4",
        "Units": 0,
        "Instructor": "STAFF\n\n\nLOPES, C.",
        "Modality": "In-Person",
        "Time": "F 1:00- 1:50p",
        "Place": "SE2 1304",
        "Final": "",
        "Max": 63,
        "Enr": 63,
        "WL": 7,
        "Req": 33,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "143",
    "courseNumber": 143,
    "courseTitle": "INFRMTION VISUALZTN",
    "fullCourseTitle": "IN4MATX 143 INFRMTION VISUALZTN",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 249,
    "maxEnrollment": 249,
    "studentsWaitlisted": 14,
    "primaryInstructor": "AHMED, N.",
    "allClassActivities": [
      {
        "Code": 36170,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "AHMED, N.",
        "Modality": "In-Person",
        "Time": "MW 2:00- 3:20p",
        "Place": "HSLH 100A",
        "Final": "Wed, Jun 11, 10:30-12:30pm",
        "Max": 249,
        "Enr": 249,
        "WL": 14,
        "Req": 356,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      },
      {
        "Code": 36171,
        "Type": "Dis",
        "Sec": "1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nSTAFF\n\n\nAHMED, N.",
        "Modality": "In-Person",
        "Time": "F 2:00- 2:50p",
        "Place": "SSH 100",
        "Final": "",
        "Max": 249,
        "Enr": 249,
        "WL": 14,
        "Req": 207,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "151",
    "courseNumber": 151,
    "courseTitle": "PROJECT MANAGEMENT",
    "fullCourseTitle": "IN4MATX 151 PROJECT MANAGEMENT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 191,
    "maxEnrollment": 191,
    "studentsWaitlisted": 11,
    "primaryInstructor": "JAMBHEKAR, S.",
    "allClassActivities": [
      {
        "Code": 36180,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "JAMBHEKAR, S.\n\n\nSTAFF",
        "Modality": "In-Person",
        "Time": "MW 6:30- 7:50p",
        "Place": "SSPA 1100",
        "Final": "TBA",
        "Max": 191,
        "Enr": 191,
        "WL": 11,
        "Req": 256,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "Web",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "153",
    "courseNumber": 153,
    "courseTitle": "CMPTR SUP COOP WORK",
    "fullCourseTitle": "IN4MATX 153 CMPTR SUP COOP WORK",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 130,
    "maxEnrollment": 130,
    "studentsWaitlisted": 4,
    "primaryInstructor": "MIN, A.",
    "allClassActivities": [
      {
        "Code": 36190,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "MIN, A.",
        "Modality": "In-Person",
        "Time": "MW 12:30- 1:50p",
        "Place": "HG 1800",
        "Final": "Wed, Jun 11, 4:00-6:00pm",
        "Max": 130,
        "Enr": 130,
        "WL": 4,
        "Req": 163,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "164",
    "courseNumber": 164,
    "courseTitle": "CHILD LRNING &MEDIA",
    "fullCourseTitle": "IN4MATX 164 CHILD LRNING &MEDIA",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 180,
    "maxEnrollment": 180,
    "studentsWaitlisted": 20,
    "primaryInstructor": "PEPPLER, K.",
    "allClassActivities": [
      {
        "Code": 36230,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "PEPPLER, K.\n\n\nSTAFF",
        "Modality": "Online",
        "Time": "TuTh 3:30- 4:50p",
        "Place": "VRTL REMOTE",
        "Final": "Tue, Jun 10, 4:00-6:00pm",
        "Max": 180,
        "Enr": 180,
        "WL": 20,
        "Req": 180,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "173",
    "courseNumber": 173,
    "courseTitle": "CONSUMER HEALTH INF",
    "fullCourseTitle": "IN4MATX 173 CONSUMER HEALTH INF",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 124,
    "maxEnrollment": 124,
    "studentsWaitlisted": 5,
    "primaryInstructor": "CHEN, Y.",
    "allClassActivities": [
      {
        "Code": 36240,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "CHEN, Y.\n\n\nSTAFF",
        "Modality": "In-Person",
        "Time": "TuTh 3:30- 4:50p",
        "Place": "DBH 1600",
        "Final": "Tue, Jun 10, 4:00-6:00pm",
        "Max": 124,
        "Enr": 124,
        "WL": 5,
        "Req": 122,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "174",
    "courseNumber": 174,
    "courseTitle": "HEALTH DATA ANALYT",
    "fullCourseTitle": "IN4MATX 174 HEALTH DATA ANALYT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 150,
    "maxEnrollment": 150,
    "studentsWaitlisted": 7,
    "primaryInstructor": "ZHENG, K.",
    "allClassActivities": [
      {
        "Code": 36250,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "ZHENG, K.\n\n\nSTAFF",
        "Modality": "In-Person",
        "Time": "MW 11:00-12:20p",
        "Place": "SSPA 1100",
        "Final": "Tue, Jun 10, 1:30-3:30pm",
        "Max": 150,
        "Enr": 150,
        "WL": 7,
        "Req": 128,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "191B",
    "courseNumber": 191,
    "courseTitle": "SENIOR DESIGN PROJ",
    "fullCourseTitle": "IN4MATX 191B SENIOR DESIGN PROJ",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 127,
    "maxEnrollment": 142,
    "studentsWaitlisted": 0,
    "primaryInstructor": "BIETZ, M. & ZIV, H.",
    "allClassActivities": [
      {
        "Code": 36350,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "BIETZ, M.",
        "Modality": "In-Person",
        "Time": "MW 3:30- 4:50p",
        "Place": "ALP 1700",
        "Final": "Mon, Jun 9, 4:00-6:00pm",
        "Max": 72,
        "Enr": 62,
        "WL": 0,
        "Req": 66,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      },
      {
        "Code": 36351,
        "Type": "Dis",
        "Sec": "A1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nBIETZ, M.",
        "Modality": "In-Person",
        "Time": "F 3:00- 3:50p",
        "Place": "ALP 2200",
        "Final": "",
        "Max": 37,
        "Enr": 33,
        "WL": 0,
        "Req": 33,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      },
      {
        "Code": 36352,
        "Type": "Dis",
        "Sec": "A2",
        "Units": 0,
        "Instructor": "STAFF\n\n\nBIETZ, M.",
        "Modality": "In-Person",
        "Time": "F 4:00- 4:50p",
        "Place": "ALP 2200",
        "Final": "",
        "Max": 38,
        "Enr": 29,
        "WL": 0,
        "Req": 31,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      },
      {
        "Code": 36355,
        "Type": "Lab",
        "Sec": "AL1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nBIETZ, M.",
        "Modality": "In-Person",
        "Time": "TBA",
        "Place": "TBA",
        "Final": "",
        "Max": 72,
        "Enr": 62,
        "WL": 0,
        "Req": 60,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      },
      {
        "Code": 36360,
        "Type": "Lec",
        "Sec": "B",
        "Units": 4,
        "Instructor": "ZIV, H.",
        "Modality": "In-Person",
        "Time": "TuTh 9:30-10:50",
        "Place": "ALP 1700",
        "Final": "Thu, Jun 12, 8:00-10:00am",
        "Max": 70,
        "Enr": 65,
        "WL": 0,
        "Req": 65,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      },
      {
        "Code": 36361,
        "Type": "Dis",
        "Sec": "B1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nZIV, H.",
        "Modality": "In-Person",
        "Time": "F 3:30- 4:50p",
        "Place": "ALP 1700",
        "Final": "",
        "Max": 70,
        "Enr": 65,
        "WL": 0,
        "Req": 65,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      },
      {
        "Code": 36365,
        "Type": "Lab",
        "Sec": "BL1",
        "Units": 0,
        "Instructor": "STAFF\n\n\nZIV, H.",
        "Modality": "In-Person",
        "Time": "TBA",
        "Place": "TBA",
        "Final": "",
        "Max": 70,
        "Enr": 65,
        "WL": 0,
        "Req": 65,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "207S",
    "courseNumber": 207,
    "courseTitle": "SEM RESRCH & WRITNG",
    "fullCourseTitle": "IN4MATX 207S SEM RESRCH & WRITNG",
    "seminarCourse": false,
    "units": 2,
    "studentsEnrolled": 7,
    "maxEnrollment": 12,
    "studentsWaitlisted": 0,
    "primaryInstructor": "REDDY, M.",
    "allClassActivities": [
      {
        "Code": 36610,
        "Type": "Sem",
        "Sec": "A",
        "Units": 2,
        "Instructor": "REDDY, M.",
        "Modality": "In-Person",
        "Time": "F 10:00-12:50p",
        "Place": "DBH 1423",
        "Final": "TBA",
        "Max": 12,
        "Enr": 7,
        "WL": 0,
        "Req": 10,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "209S",
    "courseNumber": 209,
    "courseTitle": "SEMINAR INFORMATICS",
    "fullCourseTitle": "IN4MATX 209S SEMINAR INFORMATICS",
    "seminarCourse": false,
    "units": 2,
    "studentsEnrolled": 3,
    "maxEnrollment": 40,
    "studentsWaitlisted": 0,
    "primaryInstructor": "AGAPIE, E.",
    "allClassActivities": [
      {
        "Code": 36615,
        "Type": "Lec",
        "Sec": "A",
        "Units": 2,
        "Instructor": "AGAPIE, E.",
        "Modality": "In-Person",
        "Time": "F 2:00- 3:50p",
        "Place": "TBA",
        "Final": "TBA",
        "Max": 40,
        "Enr": 3,
        "WL": 0,
        "Req": 8,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "244",
    "courseNumber": 244,
    "courseTitle": "INTR EMBED UBIQ SYS",
    "fullCourseTitle": "IN4MATX 244 INTR EMBED UBIQ SYS",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 32,
    "maxEnrollment": 60,
    "studentsWaitlisted": 0,
    "primaryInstructor": "BOZORGZADEH, E.",
    "allClassActivities": [
      {
        "Code": 36620,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "BOZORGZADEH, E.\n\n\nSTAFF",
        "Modality": "In-Person",
        "Time": "MW 11:00-12:20p",
        "Place": "SST 220B",
        "Final": "Tue, Jun 10, 1:30-3:30pm",
        "Max": 60,
        "Enr": 32,
        "WL": 0,
        "Req": 7,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "273",
    "courseNumber": 273,
    "courseTitle": "INFO TECH GLOB SUST",
    "fullCourseTitle": "IN4MATX 273 INFO TECH GLOB SUST",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 9,
    "maxEnrollment": 30,
    "studentsWaitlisted": 0,
    "primaryInstructor": "TOMLINSON, W.",
    "allClassActivities": [
      {
        "Code": 36640,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "TOMLINSON, W.",
        "Modality": "In-Person",
        "Time": "TuTh 12:30- 1:50p",
        "Place": "PCB 1200",
        "Final": "Mon, Jun 9, 1:30-3:30pm",
        "Max": 30,
        "Enr": 9,
        "WL": 0,
        "Req": 15,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "OPEN"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "285",
    "courseNumber": 285,
    "courseTitle": "INTERACTIVE TECH",
    "fullCourseTitle": "IN4MATX 285 INTERACTIVE TECH",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 44,
    "maxEnrollment": 44,
    "studentsWaitlisted": 0,
    "primaryInstructor": "EPSTEIN, D.",
    "allClassActivities": [
      {
        "Code": 36650,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "EPSTEIN, D.\n\n\nSTAFF\n\n\nSTAFF",
        "Modality": "Online",
        "Time": "TBA",
        "Place": "ON LINE",
        "Final": "TBA",
        "Max": 44,
        "Enr": 44,
        "WL": 0,
        "Req": 53,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "287",
    "courseNumber": 287,
    "courseTitle": "CAPSTONE PROJECT",
    "fullCourseTitle": "IN4MATX 287 CAPSTONE PROJECT",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 44,
    "maxEnrollment": 44,
    "studentsWaitlisted": 0,
    "primaryInstructor": "BIETZ, M.",
    "allClassActivities": [
      {
        "Code": 36660,
        "Type": "Lec",
        "Sec": "A",
        "Units": 4,
        "Instructor": "BIETZ, M.\n\n\nSTAFF\n\n\nSTAFF",
        "Modality": "Online",
        "Time": "TBA",
        "Place": "ON LINE",
        "Final": "TBA",
        "Max": 44,
        "Enr": 44,
        "WL": 0,
        "Req": 44,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "",
        "Web": "Waitl"
      }
    ]
  },
  {
    "department": "IN4MATX",
    "fullCourseNumber": "289",
    "courseNumber": 289,
    "courseTitle": "HCID IN INDUSTRY",
    "fullCourseTitle": "IN4MATX 289 HCID IN INDUSTRY",
    "seminarCourse": false,
    "units": 4,
    "studentsEnrolled": 44,
    "maxEnrollment": 44,
    "studentsWaitlisted": 0,
    "primaryInstructor": "KOLKO, J.",
    "allClassActivities": [
      {
        "Code": 36665,
        "Type": "Sem",
        "Sec": "A",
        "Units": 4,
        "Instructor": "KOLKO, J.\n\n\nSTAFF",
        "Modality": "Online",
        "Time": "TBA",
        "Place": "ON LINE",
        "Final": "TBA",
        "Max": 44,
        "Enr": 44,
        "WL": 0,
        "Req": 45,
        "Nor": null,
        "Rstr": "Bookstore",
        "Textbooks": "Web",
        "Web": "Waitl"
      }
    ]
  }
]